<?php
/**
 * Example functions to customize the banner css, either with full override, or by adding css
 * Not all functions are required, so carefully check which ones you need
 *
 * see also the file "cookiebanner.php" for the template that is included in below example
 */

/**
 * Completely override CSS generated by Complianz
 * @param string $css
 *
 * @return string
 */

function my_custom_banner_css($css){
	ob_start();
	//add css below
	?>
    .cmplz-cookiebanner {

    }
	<?php
	return ob_get_clean();
}
add_filter('cmplz_cookiebanner_css', 'my_custom_banner_css');

/**
 * IMPORTANT! This function should not be used live. It is added so the css will be regenerated on each page load, so you don't have to save the banner settings to get the new css file.
 *
 * @return void
 */
function regenerate_banner(){
	$banners = cmplz_get_cookiebanners();
	if ( $banners ) {
		foreach ( $banners as $banner_item ) {
			$banner = new CMPLZ_COOKIEBANNER( $banner_item->ID );
			$banner->save();
		}
	}
}
add_action('init', 'regenerate_banner');


/**
 * Add custom css to banner css file
 * @return void
 */
function add_my_custom_banner_css() {
	?>
    .cmplz-cookiebanner {

    }
	<?php
}
add_action( 'cmplz_banner_css', 'add_my_custom_banner_css' );

/**
 * Override cookiebanner template html
 * @param string $html
 *
 * @return string
 */
function cmplz_custom_banner_html( $path, $filename ){
	if ($filename==='cookiebanner.php') {
		return trailingslashit(WPMU_PLUGIN_DIR).'cookiebanner/cookiebanner.php';
	}
	return $path;
}
add_filter('cmplz_template_file', 'cmplz_custom_banner_html', 10, 2);
