<?php
/**
 * Example functions to customize the banner css, either with full override, or by adding css
 * Not all functions are required, so carefully check which ones you need
 *
 * see also the file "cookiebanner.php" for the template that is included in below example 
 */

/**
 * Completely override CSS generated by Complianz
 * @param string $css
 *
 * @return string
 */

function my_custom_banner_css($css){
	ob_start();
	//add css below
	?>
	.cmplz-cookiebanner {

	}
	<?php
	return ob_get_clean();
}
add_filter('cmplz_cookiebanner_css', 'my_custom_banner_css');

/**
 * Add custom css to banner css file
 * @return void
 */
function add_my_custom_banner_css() {
	?>
	.cmplz-cookiebanner {

	}
	<?php
}
add_action( 'cmplz_banner_css', 'add_my_custom_banner_css' );

/**
 * Override cookiebanner template html
 * @param string $html
 *
 * @return string
 */
function cmplz_add_social_media_category($html){
    return file_get_contents(trailingslashit(WPMU_PLUGIN_DIR).'cookiebanner.php');
}
add_filter('cmplz_banner_html', 'cmplz_add_social_media_category');