<?php

/**
 * Override cookiebanner template html
 * @param string $html
 *
 * @return string
 */

    function cmplz_custom_banner_file($path, $filename){
      if ($filename === 'cookiebanner.php' ) {
        error_log("change path to ".trailingslashit(WPMU_PLUGIN_DIR).'cookiebanner/cookiebanner.php');
        return trailingslashit(WPMU_PLUGIN_DIR).'cookiebanner/cookiebanner.php';
      }
      return $path;
    }
    add_filter('cmplz_template_file', 'cmplz_custom_banner_file', 10, 2);

/**
 * Completely override CSS generated by Complianz
 * @param string $css
 *
 * @return string
 */

 /**
  * Add custom css to banner css file
  * @return void
  */
 function add_my_custom_banner_css() {
 	?>

  @media (min-width: 1024px) {
    .cmplz-cookiebanner {
    margin: 10px;
    width: calc(100% - 20px);
    }
  }

  @media (min-width: 480px) {
    .cmplz-cookiebanner {
    display:flex;
    }
  }

  @media (max-width: 1290px) {
    .cmplz-cookiebanner .cmplz-buttons {
    display: grid;
    }
  }

  @media (max-width: 1290px) {
    .cmplz-categories-visible .cmplz-buttons {
    display: flex;
    }
    .cmplz-cookiebanner {
    }
  }

  @media (max-width: 480px) {
    .cmplz-cookiebanner .cmplz-buttons {
    display: grid;
    }
    .cmplz-cookiebanner {
    display: grid;
    }
  }

  /* cmplz-categories-visible */

  .cmplz-custom-title, .cmplz-custom-text {
    color:#043959;
    font-family:inherit;
  }

  .cmplz-custom-title {
    font-size:18px;
    font-weight:600;
  }

  .cmplz-cookiebanner .cmplz-categories .cmplz-category .cmplz-category-header {
    padding: 0 10px!important;
  }

  .cmplz-categories .cmplz-category {
    background: white!important;
    border: 1px solid #eff3f7;
  }

  .cmplz-custom-text {
    font-size: 14px;
    margin: 20px 0;
  }

  .cmplz-categories-visible .cmplz-btn {
    min-width:unset!important;
  }
    button.cmplz-btn {
    font-size: 14px!important;
    font-family: inherit;
  }
  .cmplz-categories-visible .cmplz-message {
    display:none;
  }

  .cmplz-cookiebanner .cmplz-categories .cmplz-category .cmplz-description {
    padding: 0px 10px 0px 10px!important;
  }
  .cmplz-cookiebanner .cmplz-categories .cmplz-category {
    padding: 5px;
  }

  .cmplz-cookiebanner .cmplz-categories .cmplz-category .cmplz-category-header {
    grid-template-columns: 1fr auto 0px!important;
  }

  .cmplz-cookiebanner .cmplz-categories .cmplz-category .cmplz-category-header .cmplz-category-title {
    font-size: 18px;
  }

  .cmplz-cookiebanner.cmplz-categories-visible .cmplz-body > div {
    width: 100%;
  }

  .cmplz-cookiebanner .cmplz-divider, .cmplz-cookiebanner .cmplz-header,
  .cmplz-manage-third-parties, .cmplz-close, .cmplz-title, .cmplz-logo
    {
    display:none;
    }

  .cmplz-custom-message {
    display:flex;
    flex-direction: column;
    align-content: flex-start;
  }

  .cmplz-categories-visible {
    left:50%!important;
    top:50%!important;
    transform: translate(-50%, -50%)!IMPORTANT;
    position:absolute!important;
    width:580px!important;
    flex-direction: column;
    height: fit-content;
  }

  .cmplz-cookiebanner .cmplz-categories-visible .cmplz-header a.cmplz-close,
  .cmplz-categories-visible .cmplz-header .cmplz-logo,
  .cmplz-categories-visible .cmplz-header .cmplz-title,
  {
    display:unset!important;
  }

  .cmplz-cookiebanner {
    box-shadow: rgba(0, 0, 0, 0.45) 0px 25px 20px -20px;
  }

  .cmplz-categories-visible {
    opacity: 0;
    animation: opacityOn 1s normal forwards;
    animation-timing-function: ease-in;
    animation-delay: 0s;
  }

  @keyframes opacityOn {
  0% {
  opacity: 0.2;
  }
  25% {
  opacity: 0.4;
  }
  50% {
  opacity: 0.6;
  }
  75% {
  opacity: 0.9;
  }
  100% {
  opacity: 1;
  }
  }

  .cmplz-buttons {
    flex-direction:row-reverse!important;
    border:none;
    border-radius:0px;
  }

 	<?php
 }
 add_action( 'cmplz_banner_css', 'add_my_custom_banner_css' );

 /**
 * IMPORTANT! This function should not be used live. It is added so the css will be regenerated on each page load, so you don't have to save the banner settings to get the new css file.
 *
 * @return void
 */
function regenerate_banner(){
	$banners = cmplz_get_cookiebanners();
	if ( $banners ) {
		foreach ( $banners as $banner_item ) {
			$banner = new CMPLZ_COOKIEBANNER( $banner_item->ID );
			$banner->save();
		}
	}
}
add_action('init', 'regenerate_banner');
