<?php

/**
 * Override cookiebanner template html
 * @param string $html
 *
 * @return string
 */

function cmplz_custom_banner_file($path, $filename){
  if ($filename === 'cookiebanner.php' ) {
    error_log("change path to ".trailingslashit(WPMU_PLUGIN_DIR).'cookiebanner/cookiebanner.php');
    return trailingslashit(WPMU_PLUGIN_DIR).'cookiebanner/cookiebanner.php';
  }
  return $path;
}

add_filter('cmplz_template_file', 'cmplz_custom_banner_file', 10, 2);

/**
 * Completely override CSS generated by Complianz
 * @param string $css
 *
 * @return string
 */

 /**
  * Add custom css to banner css file
  * @return void
  */
 function add_my_custom_banner_css() {
 	?>

 	<?php
 }
 add_action( 'cmplz_banner_css', 'add_my_custom_banner_css' );

 /**
 * IMPORTANT! This function should not be used live. It is added so the css will be regenerated on each page load, so you don't have to save the banner settings to get the new css file.
 *
 * @return void
 */
function regenerate_banner(){
	$banners = cmplz_get_cookiebanners();
	if ( $banners ) {
		foreach ( $banners as $banner_item ) {
			$banner = new CMPLZ_COOKIEBANNER( $banner_item->ID );
			$banner->save();
		}
	}
}
add_action('init', 'regenerate_banner');
